### ISSUE TITLE
pymavlink_source message debug printing garbage

### ISSUE THREAD

**Issue by dickfusco** [deptofdefense/gr-uaslink#3]
This is probably a pmt issue unrelated to gr-uaslink, but does anyone know why I get garbage in the console when I run the test_pymavlink_source flow graph?  I think the issue is coming in with `to_pmt()`

![image](https://user-images.githubusercontent.com/5683743/30658149-d138ba52-9e07-11e7-87a5-4039c078d7e9.png)

**Comment by flynn378** [comment]
The data that comes from a mavlink message in encoded into a binary format before it goes through the pmt message passing.  To see the actual contents of the message decoded you will need to add the following line after line 60 
line 60 = if(self.message!=None):
print (self.message)

**Comment by dickfusco** [comment]
Got it, that works--thanks
