### ISSUE TITLE
control gui doesnt send control messages to test_pymvalink_source_sint_sitl

### ISSUE THREAD

**Issue by ognlvnt** [deptofdefense/gr-uaslink#5]
Hi there, we tried to send control commands when the SITL is open but we noticed that control gui doesnt send messages from control_gui.grc(zmq sub sink) to the pymavlink_source_sink_sitl.grc. We should be able to see control commands at the software in the loop terminal but we cant. And also we think there is a problem with the message format that passing between blocks is wrong. We see strange characters when trying  to visualize whats going on. Any ideas? Appreciate for any help.

**Comment by flynn378** [comment]
The message from the control GUI is encoded into bits, thus looking at them with a ASCII viewer will be strange characters.  Also make sure you are using control_gui_override_control.py as the control GUI to send correctly formatted bits.

**Comment by flynn378** [comment]
I tested this again, the connection string for mavlink control should be changed to '127.0.0.1:14560'.   The messages that are being send are rc override messages for left, right etc  Starting with the map and then performing a takeoff should show the process of arming the motors in the console.  You have to hold the buttons down on the control GUI SITL move the copter.  Think of this a a remote for a UAS with center stick 1500, it takes 1600 to move at all.

**Comment by ognlvnt** [comment]
Hi,
Thanks a lot. But after I changed the connection string open the control_gui_override_control.py and test_pymavlink_source_sink_serial.grc connected pixhawk and I couldnt get messages even I pressed buttons on the control gui. SITL doesnt respond to control gui. There is a photo in the attachments.

Best.

![serial](https://user-images.githubusercontent.com/16335543/39922786-6f58872a-5529-11e8-9e7f-6809fb7a4fb9.png)

**Comment by flynn378** [comment]
You need to start the SITL with the command
sim_vehicle.py --console --map
From within ArduCopter  that console will show the arm command and you can see movement on the map

**Comment by ognlvnt** [comment]
I guess  I sent the wrong photo but I was triying with SITL all the time and still not getting any message at the test_pymavlink_source_sink_serial.grc flowgraph. There should be something else. Is there any kind of tips or tricks? In my opinion  there might be another problem because I did this according to your instructions. 
Best.

**Comment by flynn378** [comment]
Since you are testing with serial and SITL, then you need to have the computer connected through a USB port to a hardware flight controller.  You also need to configure the Connection String parameter within pymavlink_source_sink_pp to be the device that is created when you plug it into the computer, which can be found with dmesg.
 For SITL you will need to use the Connection String 'tcp:127.0.0.1:5763'
for the pymavlink_source_sink_pp.

**Comment by flynn378** [comment]
The Message Debug is printing the data from the control GUI.  The data from the control GUI is an array of 64 bits.  It is not human readable with Message Debug.

**Comment by ognlvnt** [comment]
So what am I doing wrong? we still cant takeoff from the SITL by using control gui override control.

**Comment by flynn378** [comment]
I was wrong about the message coming from the control GUI, that message should print out information that is human readable from the Message Debug where you are not seeing anything.  Try disabling everything except the ZMQ block and the message debug port.  At that point the SITL will not be needed.  It will test that the ZMQ message can be sent and received.  Then just hit takeoff from the control GUI, that will start it sending messages.  If they do not come through you can you use wireshark to look at the ports.  It may be a firewall rule if your company auto configures a firewall on your computer.

**Comment by ognlvnt** [comment]
Hi Toby,
I checked everything you said. listened tcp ports checked firewall etc but nothing changed so far. I strongly belive that I did everything correct but inside the control gui override control code I cannot see messages after the line shown at the photo below. I doubt Self.zmqc function doesnt work properly. When I tried to send a test strobe to zmq sub port it was working on another flowgraph. If possible could you test on your pc please? I became very curious about this issue.
Regards.

![latest](https://user-images.githubusercontent.com/16335543/40234222-a83802de-5aae-11e8-94a6-7cedcce61593.png)
zmq test flow:

![zmq test](https://user-images.githubusercontent.com/16335543/40234492-beef0486-5aaf-11e8-99fa-b291846a546b.png)

**Comment by flynn378** [comment]
I checked this again and it works well for me.  The same code that is the repo was used for a hackfest event with 8 teams and other people using it without any issues.  You do have to click takeoff before any other buttons will work on the GUI.  I assume you are running GNURadio setenv in the terminal before starting the control GUI control app.

**Comment by ognlvnt** [comment]
I downloaded the clean code from the source again it doesnt work could you tell exact steps? we open control gui first then open the flowgraph from the grc. the code at the repo doesnt work unless we change the udp string. Could you send your code so we can see difference or what we do wrong

**Comment by flynn378** [comment]
For the steps please refer to the link in the readme to the long presentation.
In general
in one terminal source the GNURadio environment and start the control gui

in another terminal start GRC after sourcing the  GNURadio enviroment
open
test_pymavlink_source_sink_sitl_zmq.grc (this one has the correct settings for mavlink_control)
start the SITL using the command
sim_vehicle.py --console --map
from  the ArduCopter directory

Run test_pymavlink_source_sink_sitl_zmq
click takeoff on the GUI, messages should flow through the system.
If they are not coming out of teh ZMQ then the issues has nothing to do with mavlink controller or the SITL interface (those blocks can be disabled and a debug message block attached to the ZMQ block)

Pay careful attention to any error message displaying on the control_gui terminal.  You may have a run-time linker error from missing path libraries.  Since there are multiple threads it is important to look after start up and when you hit a button.  You may need to run ldconfig to get the libraries to work also.

**Comment by ognlvnt** [comment]
Hello again sorry to bother you but I read the documentation and went through each steps you mentioned. Ports are correct. SITL works and libraries working fine. I tested zmq source and sinks with pmt test messages in gnuradio. From test_pymavlink_source_sink_sitl_zmq I can see heartbeat. Listened TCP port 14000 and I believe I did everything correctly. I am pretty sure that control_gui_override_control.py doesnt send control messages over zmq blocks to the test_pymavlink_source_sink_sitl_zmq flow graph. Is there a change in the control gui code you might forgot to mention?
Regards.

**Comment by flynn378** [comment]
I double checked and the code that is checked in is the code I have. Also the computers for the hackfest event were all configured from the public repo directly and they all worked.  Can you pastbin the contents of the terminal you used to start the control gui from the command to start it to after clicking the take off button, and maybe a few seconds after that.

**Comment by ognlvnt** [comment]
Hi, I finally managed to takeoff in SITL on another pc. Issue was the from a dependency. You were right. Thanks for your patience. By the way in UHD block rf freq shows uhd_tune_request class. Is it possible to tune specific center freq from osmocom source?
Regards.
