### ISSUE TITLE
Zmq message problem

### ISSUE THREAD

**Issue by BurakKskn** [deptofdefense/gr-uaslink#6]
I'm  trying to run examples but I can't get messages from control_gui. Can anyone help me about this?

**Comment by flynn378** [comment]
are you running control_gui_override_control.py from the apps directory.  The control_gui.grc is a template for the basic GUI but does not actually create messages.

**Comment by BurakKskn** [comment]
I'm running control_gui_override_control.py and test_pymavlink_source_sink_serial.grc. When I start test_pymavlink_source_sink_serial.grc  I get "Udp port must be specified as host:port" error. In mavlink_control block I changed the connection string from "udpout:127.0...." to "127.0.0.1:...". But still I can't get messages from control.

**Comment by flynn378** [comment]
For mavlink_control the change to "127.0.0.1:..." is a correct change.  This is a test for connecting to serial device so you will need to make sure the serial device is connected to the computer fro this to work.

**Comment by BurakKskn** [comment]
I think I made a mistake in my previous message. I'm using test_pymavlink_source_sink_sitl.grc but I can't control the vehicle in the SITL. (for control I'm using control_gui_override_control.py and using Ardupilot's SITL.)

**Comment by BurakKskn** [comment]
![mavlink_control](https://user-images.githubusercontent.com/35131015/40125162-ea2b2da6-5932-11e8-9ca6-e09071526b30.png)
when a comamand received to mavlink_control block I think this function is working. suppose to print "receive message" when a command receive from ZMQ SUB message source but when I tried to run the example (SITL) I can't see that message.

**Comment by BurakKskn** [comment]
I think there is a problem about dependency. I reinstalled gnuradio and oot modules and test_pymavlink_source_sink_sitl.grc is working. Thanks for help. But I have a different problem now. I'm trying to control raspberry pi (in raspberry pi I'm using uhd_psk_burst_control_rpi.grc) from my pc with uhd_psk_burst_control_pc.grc but it isn't working. Are they the right flow graphs to control rpi from pc? And when I run the uhd_psk_burst_control_pc.grc QT GUI don't show anything is that normal?

**Comment by flynn378** [comment]
Those are the correct flow graphs. You need to make sure the frequencies are the same on both radios. There is not  a QT GUI for either uhd_psk_burst_control_pc or uhd_psk_burst_control_rpi.grc.  For the rpi you will need to make sure the pixhawk shows up as the same USB port in the default settings.
